config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'profile', to: 'users#show', as: :profile

  root 'welcome#home'

  post '/lists/:id' => 'lists#destroy', :as => :destroy_list

  resources :users do
    resources :lists
  end

  resources :lists do
    resources :ratings, only: [:create]
  end

  match '*path' => redirect('/'), via: :get

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord

validates :title, :number1, :number2, :number3, :number4, :number5, presence: true

after_save :change_title

serialize :found_lists

has_many :topics, through: :list_topics
has_many :list_topics
belongs_to :user, optional: true

has_many :ratings, foreign_key: 'rated_id'
has_many :raters, through: :ratings, class_name: "User", foreign_key: 'rated_id'

scope :non_user_lists, lambda { |current| where.not(:user_id => current.id) }

    def list_topics_attributes=(attributes)
      self.list_topics.destroy_all
      attributes.values.each do |attr| 
        attr.values[0].each do |id| 
        if !id.blank? 
          topic = Topic.find_by(id: id)
          self.list_topics.build(:topic => topic)
        end
      end
    end
    end

    def self.highest_rating
       List.all.order('average_rating DESC')
    end

    def change_title
      unless self.title.match(/(Top 5 Greatest){1}\s/)
        self.title = "Top 5 Greatest #{self.title}"
        self.save
      end
    end 

end

app/models/list_topic.rb
class ListTopic < ApplicationRecord

  belongs_to :list, :optional => true
  belongs_to :topic, :optional => true

  scope :topic_finder, lambda { |item| where(topic_id: Topic.find(item).id) }

end

app/models/rating.rb
class Rating < ApplicationRecord

after_save :calculate_average

belongs_to :rater, class_name: "User", optional: true
belongs_to :rated, class_name: "List", optional: true

private

def calculate_average
  @list = List.find_by(id: self.rated_id)
  @list.average_rating = @list.ratings.average(:rating).to_i
  @list.save
end 

end

app/models/topic.rb
class Topic < ApplicationRecord

has_many :lists, through: :list_topics
has_many :list_topics

end

app/models/user.rb
class User < ApplicationRecord

serialize :found_lists
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  has_many :ratings, foreign_key: 'rater_id'
  has_many :rated, through: :ratings, class_name: "List", foreign_key: 'rater_id'

  has_many :lists
  
    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_filter :authenticate_user!
  protect_from_forgery with: :exception


def after_sign_in_path_for(resource)
  request.env['omniauth.origin'] || root_path
end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :setup, only: [:create, :index]
  skip_before_filter :authenticate_user!, :only => [:index, :show, :create]

  def new
    @user = User.find_by(id: current_user.id)
    @list = List.new
    @all_topics = Topic.all
  end

  def create
    if current_user
      @user = User.find_by(id: current_user.id)
        if params[:list_topic]
          found
          render :index
        else
          @list = List.new(list_params)
          binding.pry
            if @list.save
              redirect_to user_list_path(@user, @list)           
            else
              render :new
            end
        end
    else
      found
      render :index
    end 
  end

  def show
    if List.find_by(id: params[:id]) != nil
      @list = List.find(params[:id])
      if current_user
        @user = @list.user
        @rating = Rating.new
        @list_rating = @list.average_rating
      end
    else 
      redirect_to "/"
    end
  end

  def edit
    if params[:user_id]
      @list = List.find(params[:id])
      @user = User.find(params[:user_id])
      @list2 = List.new
      @list.title = @list.title.sub(/(Top 5 Greatest){1}\s/, '')
      @all_topics = Topic.all
    else
      flash[:notice] = "You have to be the list creator to edit."
      redirect_to user_path(current_user.id)
      end   
  end

  def index
  end 

  def update
    @list = List.find(params[:id])
    @user = User.find_by(id: params[:user_id])
    if @list.update(list_params)
      @list.change_title
      redirect_to user_list_path(@user, @list)
    else
      render :edit
    end 
  end

  def destroy
    @list = List.find(params[:id])
    @user = @list.user
    @list.delete
    redirect_to user_path(@user)
  end  

private

  def list_params
    params.require(:list).permit(:title, :number1, :number2, :number3, :number4, :number5, :user_id, :list_topics_attributes => [topic_id: []])
  end

  def find_list
    @list = List.find(params[:id])
  end

  def found
    @found = List.joins(:topics).merge(Topic.where(id: params[:list_topic][:topic_id].delete_if(&:empty?)))
  end 

  def setup
    @recent = List.all.order(created_at: :desc)
    @submit = ListTopic.new
    @highest = List.highest_rating[0..9]
    @all_topics = Topic.all
    @lists = List.all
  end   

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

def create
  @rating = Rating.new(rating_params)
  @list = List.find_by(id: params[:list_id])
  @rating.rated_id = @list.id
  # @rating.rater_id = current_user.id
  # Feature to possibly later implement
  @rating.save
  redirect_to list_path(@list)
end

private

def rating_params
  params.require(:rating).permit(:rating)
end 

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user      
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    if !user_signed_in?
      redirect_to '/'
    end
    @lists = current_user.lists
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

skip_before_filter :authenticate_user!

  def home
    unless !user_signed_in?
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/rating_helper.rb
module RatingHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/layouts/_logged_in.erb
<li class="nav-item"><%= active_link_to "Profile", user_path(current_user) %></li>
<li class="nav-item"><%= active_link_to "Lists", lists_path, active: [['lists'], ['index']] %></li>
<li class="nav-item"><%= active_link_to "Add List", new_list_path, active: [['lists'], ['new']] %></li>
<li class="nav-item"><%= active_link_to "Log Out", destroy_user_session_path, :method=>:delete %></li>

app/views/layouts/_messages.html.erb
<%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
<%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
<%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>

app/views/layouts/_notsignedin.html.erb
<li class="nav-item"><%= active_link_to "Lists", lists_path, active: [['lists'], ['index']] %></li>
<li class="nav-item"><%= active_link_to "Sign Up", new_user_registration_path, active: /\bsign_up/ %></li>
<li class="nav-item"><%= active_link_to "Login", new_user_session_path, active: /\bsign_in/ %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Top5</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </head>
  <body data-spy="scroll">
    <div id="fb-root"></div>
      
      <header id="header" class="header">  
        <div class="container">            
            <h1 class="logo pull-left">
                <a class="scrollto" href="/lists">
                  <span class="logo-title">Top5</span>
                </a>
            </h1><!--//logo-->              
            <nav id="main-nav" class="main-nav navbar-right" role="navigation">
                <div class="navbar-header">
                  <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button><!--//nav-toggle-->
                </div><!--//navbar-header-->       
                <div class="navbar-collapse collapse" id="navbar-collapse">
                  <div id="nr">
                    <ul class="nav navbar-nav">
                        <% if current_user %>
                          <%= render partial: "layouts/logged_in" %>
                        <% else %>
                          <%= render partial: "layouts/notsignedin" %>
                        <% end %>
                    </ul><!--//nav-->
                </div>
                </div><!--//navabr-collapse-->
            </nav><!--//main-nav-->
        </div>
    </header><!--//header-->
        <div class="container">
          <div>
            <br>
            <br>
            <br>
          </div>  
          <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="container text-center">
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= pluralize(list.errors.count, "error") %>
        prohibited this post from being saved:
      </h3>

      <ul>
          <li>All Boxes Must Be Filled In</li>
      </ul>
     </div>
      <br>
  <% end %>

  <br><%= f.label "Top Five Greatest:" %>
  <%= f.text_field :title %><br>
  <%= f.hidden_field :user_id, value: user.id %>
  <br><%= f.label "#1" %>
  <%= f.text_field :number1 %>
  <br><%= f.label "#2" %>
  <%= f.text_field :number2 %>
  <br><%= f.label "#3" %>
  <%= f.text_field :number3 %>
  <br><%= f.label "#4" %>
  <%= f.text_field :number4 %>
  <br><%= f.label "#5" %>
  <%= f.text_field :number5 %>
<br>
<br>

 <%= f.fields_for :list_topics, list.list_topics.build do |ff| %>
  <%= ff.label "Edit Topic:"  %><br>
  <%= ff.collection_select(:topic_id, Topic.all, :id, :name, {:selected => list.topic_ids}, {multiple: true}) %>
 <% end %>

 <%= f.submit %>
</div>

app/views/lists/edit.html.erb
<h1>EDIT</h1>
          
<br>

<%= form_for @list, url: user_list_path(@list.user, @list), method: "patch" do |f| %>

<%= render partial: "form", locals: {list: @list, user: @user, f: f} %>

<% end %>

app/views/lists/index.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-lg-4">
       <h3>Highest Rated Lists</h3>
      <% @highest.each do |list| %>
      <li><%= link_to list.title, list_path(list) %> <% if list.average_rating && list.average_rating > 0 %><br>Average Rating: <%= list.average_rating %><% end %>
      <% end %>
    </div>
    <div class="col-lg-4">
        <h3>Most Recent Top 5 Lists</h3>
      <% @recent.each do |list| %>
      <li style="font-size: 150%"><%= link_to list.title, list_path(list) %>
      <% end %>
    </div>
    <div class="col-lg-4">
          <% if @found %>
      <h3>Found Lists</h3>
      <% @found.each do |list| %>
    <li><%= link_to list.title, list_path(list) %></li>
  <% end %>
  <% end %>

    <h3>Search Lists By Topic</h3>
      <%= form_for @submit, url: lists_path do |f| %>
      <%= f.collection_select(:topic_id, @all_topics, :id, :name, {}, {multiple: true}) %>
      <%= f.submit "Search Lists By Topic" %>
    <% end %>
    </div>
  </div>
</div>
</div>

app/views/lists/new.html.erb
  <%= form_for @list, url: user_lists_path(@user, @list) do |f| %> 

  <%= render partial: "form", locals: {list: @list, user: @user, f: f} %>

  <% end %>

app/views/lists/show.html.erb
<div class="container text-center">
  <h2 class="space"><%= @list.title %></h2>
  #1. <%= @list.number1 %><br>
  #2. <%= @list.number2 %><br>
  #3. <%= @list.number3 %><br>
  #4. <%= @list.number4 %><br>
  #5. <%= @list.number5 %><br>
<br>
  <p>Rating: <%= @list_rating %><p>
  <p class="space">Topics:</p>
    <% @list.topics.each do |topic| %>
      <i><%= topic.name %></i>
  <% end %>
  <br>
  <br>
  <% if current_user %>
      <%= form_for @rating, url: list_ratings_path(@list, @rating) do |rate| %>
      <%= rate.number_field :rating, :in => 1..10 %>
      <%= rate.submit "Rate This List (1-10)" %>
    <% end %>
    <% if current_user.lists.exists?(@list.id) %>
          <br>
      <%= link_to "Edit List", edit_user_list_path(@list.user, @list) %><br>
      <%= link_to 'Delete List', destroy_list_path(@list), method: "post" %>
    <% end %>
  <% end %>
</div>

app/views/ratings/_rating.html.erb
<% if list.average_rating == nil %>
<h4>Average Rating: <%= list.ratings.last.rating %></h4>
<% else %>
<h4>Average Rating: <%= list.average_rating %></h4>
<% end %>

app/views/ratings/create.js.erb
$('#lists').append("<%=j(render('ratings/rating', :list => @list)) %>")  

app/views/ratings/new.html.erb
<br>
<%= form_for @rating do |rate| %>
<%= rate.number_field :rating, :in => 1..10 %>
<%= rate.submit "Rate This List (1-10)" %>
<% end %>
<br>
<br>

app/views/users/show.html.erb
<div class="container text-center">
  <h3>All Your Lists</h3>
  <% @lists.each do |list| %>
  <li><%= link_to list.title, user_list_path(list.user, list) %></li>
  <% end %>
</div>

app/views/welcome/home.html.erb
<section id="promo" class="promo section offset-header">
    <div class="container text-center">
        <div class="logo-text">
            <h2 class="title">Top<span class="highlight">5</span></h2>
            <p class="intro">Welcome to Top5, where we finally figure out who truly is the greatest!</p>
        </div>
            <div class="aws">
                   <div class="btns">
                     <%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-cta-secondary position1"  %>
            <%= link_to "Login", new_user_session_path, :class => "btn btn-cta-primary position2" %>
            </div>
        </div>
    </div><!--//container-->
</section>
<footer id="footer">
</footer>